file_properties:
  image:
    absolute_path: 'public/images/image'
    link_path:     'public/images/image'
supported_mime_types:
  - extension:     'jpeg'
    mime_type:     'image/jpeg'
    type:          'image'
  - extension:     'jpg'
    mime_type:     'image/jpeg'
    type:          'image'
  - extension:     'm4v'
    mime_type:     'video/mv4'
    type:          'video'
  - extension:     'mov'
    mime_type:     'video/quicktime'
    type:          'video'
  - extension:     'mp4'
    mime_type:     'video/mp4'
    type:          'video'
  - extension:     'png'
    mime_type:     'image/png'
    type:          'image'
  - extension:     '.htc'
    mime_type:     'text/x-component'
    type:          'text'
